const $=id=>document.getElementById(id);
const storeKey='adhdHealthOSV4';
let db=JSON.parse(localStorage.getItem(storeKey)||'{"entries":[],"settings":{"theme":"light","scheme":"copper"},"profile":null}');
const adhdMetrics=[{id:'focus',label:'Focus',weight:25,inverse:false},{id:'initiation',label:'Task initiation',weight:20,inverse:false},{id:'switching',label:'Task switching',weight:15,inverse:false},{id:'emotional',label:'Emotional regulation',weight:15,inverse:false},{id:'noise',label:'Mental noise',weight:15,inverse:true},{id:'irritability',label:'Irritability',weight:10,inverse:true}];
const moodMetrics=[{id:'mood',label:'Mood'},{id:'motivation',label:'Motivation'},{id:'anxiety',label:'Anxiety'},{id:'irritMood',label:'Irritability'}];
let vals={focus:5,initiation:5,switching:5,emotional:5,noise:5,irritability:5,mood:5,motivation:5,anxiety:5,irritMood:5};
function set(id,v){const e=$(id);if(e)e.textContent=v} function html(id,v){const e=$(id);if(e)e.innerHTML=v}
function clamp(n,min,max){return Math.max(min,Math.min(max,n))} function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:null} function rating(s){return s>=90?'Excellent':s>=75?'Good':s>=60?'Average':s>=40?'Poor':'Severe'}
function save(){localStorage.setItem(storeKey,JSON.stringify(db));render()} function mins(t){if(!t)return null;const [h,m]=t.split(':').map(Number);return h*60+m} function fmt(m){if(m==null||Number.isNaN(m))return'--';m=Math.round(m)%1440;return`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`} function diff(a,b){let x=mins(a),y=mins(b);if(x==null||y==null)return null;if(y<x)y+=1440;return y-x}
function val(id,d=0){const e=$(id);return e?Number(e.value)||d:d} function str(id){const e=$(id);return e?e.value:''}
function applySettings(){document.body.className='';if(db.settings.theme==='dark')document.body.classList.add('dark');if(db.settings.theme==='amoled')document.body.classList.add('amoled');if(db.settings.scheme&&db.settings.scheme!=='copper')document.body.classList.add(db.settings.scheme);if($('theme'))$('theme').value=db.settings.theme||'light';if($('scheme'))$('scheme').value=db.settings.scheme||'copper'}
function buildSliders(list,wrapId){const wrap=$(wrapId);wrap.innerHTML='';list.forEach(m=>{const row=document.createElement('div');row.className='row';row.innerHTML=`<div class="rowTop"><span>${m.label}</span><span id="${m.id}Val">${vals[m.id]}</span></div><input id="${m.id}" type="range" min="0" max="10" value="${vals[m.id]}">`;wrap.appendChild(row);$(m.id).addEventListener('input',e=>{vals[m.id]=Number(e.target.value);set(m.id+'Val',vals[m.id]);render()})})}
function engineADHD(){let weighted=0;adhdMetrics.forEach(m=>weighted+=(m.inverse?10-vals[m.id]:vals[m.id])*m.weight);const score=Math.round(weighted/10);const exec=Math.round(((vals.focus+vals.initiation+vals.switching+vals.emotional)/40)*100);const symptom=Math.round((((10-vals.noise)+(10-vals.irritability))/20)*100);return{score,exec,symptom,rating:rating(score)}}
function engineSleep(){const start=str('sleepTime')||str('bedtime');let dur=diff(start,str('wakeTime'));dur=dur==null?8:dur/60;const latency=str('sleepTime')&&str('bedtime')?diff(str('bedtime'),str('sleepTime')):null;const quality=val('quality',8),wakings=val('wakings',1);let durScore=dur<=0?0:dur<=8?(dur/8)*50:dur<=9?50:Math.max(35,50-((dur-9)*5));const score=Math.round(clamp(durScore+(quality/10)*40+Math.max(0,10-wakings*2),0,100));return{score,rating:rating(score),risk:score>=75?'LOW':score>=60?'MEDIUM':'HIGH',duration:Number(dur.toFixed(1)),latency,wakings,quality,debt:Number(Math.max(0,8-dur).toFixed(1))}}
function adherence(){const es=db.entries.slice(-30);return es.length?Math.round(es.filter(e=>!e.med.missed).length/es.length*100)+'%':'--'}
function engineMed(a,s){const crash=clamp(val('crashSeverity',5),0,10),caffeine=val('caffeine',100),protein=str('protein')==='yes',missed=str('missedDose')==='yes';const lifestyle=(protein?5:-3)-(caffeine>300?10:caffeine>150?5:0)-(missed?25:0);const score=Math.round(clamp(a.score*.7+(s.score-50)*.2-crash*3+lifestyle+20,0,100));let risk='HIGH';if(crash<=3&&s.score>=75&&score>=75)risk='LOW';else if(crash<=6&&s.score>=60&&score>=60)risk='MEDIUM';return{score,rating:rating(score),risk,lifestyle,missed}}
function engineMood(){const p=(vals.mood+vals.motivation+(10-vals.anxiety)+(10-vals.irritMood))/40;return{score:Math.round(p*100),rating:rating(Math.round(p*100))}}
function engineHealth(s){let score=50;if(s.score>=75)score+=20;else if(s.score<60)score-=10;const protein=val('proteinGrams',str('protein')==='yes'?100:0);if(protein>=150)score+=15;else if(protein>=80)score+=10;if(val('water')>=2)score+=5;if(str('gym')==='yes')score+=10;if(val('steps')>=val('goalSteps',8000))score+=10;if(val('caffeine',100)>300)score-=15;return{score:Math.round(clamp(score,0,100)),rating:rating(score)}}
function current(){const adhd=engineADHD(),sleep=engineSleep(),med=engineMed(adhd,sleep),mood=engineMood(),health=engineHealth(sleep);const dailyScore=Math.round(adhd.score*.32+sleep.score*.2+med.score*.22+mood.score*.12+health.score*.14);const risk=sleep.score<60||med.risk==='HIGH'||val('crashSeverity',5)>=7?'HIGH':sleep.score<75||med.risk==='MEDIUM'?'MEDIUM':'LOW';return{date:new Date().toISOString(),values:{...vals},adhd,sleep,med,mood,health,dailyScore,risk,medName:str('medName'),dose:str('dose'),medTime:str('medTime'),caffeine:val('caffeine',100),proteinBreakfast:str('protein')==='yes',sideEffects:[...document.querySelectorAll('.side:checked')].map(x=>x.value),crash:{time:str('crashTime'),recovery:str('recoveryTime'),severity:val('crashSeverity',5),duration:diff(str('crashTime'),str('recoveryTime'))||val('recoveryMinutes'),symptoms:''},hyperfocus:{activity:str('hyperfocusActivity'),minutes:val('hyperfocusMinutes'),type:str('hyperfocusType'),afterCrash:str('hyperfocusAfterCrash')==='Yes'},weight:val('weight'),bodyFat:val('bodyFat'),steps:val('steps'),water:val('water'),proteinGrams:val('proteinGrams'),gym:str('gym'),journal:{win:str('journalWin'),struggle:str('journalStruggle'),observation:str('journalObservation')}}}
function averageCrashTime(){const t=db.entries.filter(e=>e.crash&&e.crash.time).map(e=>mins(e.crash.time));return t.length?fmt(avg(t)):'--'} function avgCrashSeverity(){const v=db.entries.filter(e=>e.crash&&e.crash.severity).map(e=>e.crash.severity);return v.length?avg(v).toFixed(1)+'/10':'--'}
function bestDose(){const groups={};db.entries.forEach(e=>{if(e.dose){groups[e.dose]=groups[e.dose]||[];groups[e.dose].push(e.med.score)}});const sorted=Object.entries(groups).map(([k,v])=>[k,avg(v)]).sort((a,b)=>b[1]-a[1]);return sorted.length?sorted[0][0]:'--'}
function commonActivity(){const c={};db.entries.forEach(e=>{const a=e.hyperfocus&&e.hyperfocus.activity;if(a)c[a]=(c[a]||0)+1});const s=Object.entries(c).sort((a,b)=>b[1]-a[1]);return s.length?s[0][0]:'--'}
function focusReadiness(e){let score=Math.round(e.adhd.exec*.35+e.adhd.score*.25+e.sleep.score*.2+e.med.score*.15+e.mood.score*.05);if(e.crash.severity>=7)score-=10;if(e.caffeine>300)score-=5;score=clamp(score,0,100);return{score,label:score>=80?'READY':score>=60?'OK':score>=40?'FRAGILE':'LOW'}}
function coach(e){const out=[];if(e.sleep.score<60)out.push('Sleep is limiting focus. Keep important work early and light.');if(e.med.risk==='HIGH')out.push('Crash risk is high. Prioritise food, hydration and avoid extra caffeine.');if(e.adhd.exec<60)out.push('Executive function is low. Use 5-minute task starts.');if(e.values.noise>=7)out.push('Mental noise is high. Use one list, one task, one tab.');if(!out.length)out.push('Good readiness. Use the morning/early afternoon for high-value tasks.');return out}
function insights(){const es=db.entries,out=[];if(es.length<3)out.push('Need 3+ entries for stronger pattern insights.');const high=es.filter(e=>e.sleep.duration>=8),low=es.filter(e=>e.sleep.duration<7);if(high.length&&low.length)out.push(`8h+ sleep days average focus ${avg(high.map(e=>e.values.focus)).toFixed(1)} vs ${avg(low.map(e=>e.values.focus)).toFixed(1)} on <7h days.`);const py=es.filter(e=>e.proteinBreakfast),pn=es.filter(e=>!e.proteinBreakfast);if(py.length&&pn.length)out.push(`Protein breakfast med effectiveness: ${avg(py.map(e=>e.med.score)).toFixed(1)}% vs ${avg(pn.map(e=>e.med.score)).toFixed(1)}%.`);if(es.some(e=>e.crash.time))out.push(`Average crash time is ${averageCrashTime()}.`);return out}
function weekly(){const es=db.entries.slice(-7);if(!es.length)return'No weekly data yet.';return`Entries: ${es.length}\nADHD avg: ${avg(es.map(e=>e.adhd.score)).toFixed(1)}\nSleep avg: ${avg(es.map(e=>e.sleep.score)).toFixed(1)}\nMedication avg: ${avg(es.map(e=>e.med.score)).toFixed(1)}%\nDaily avg: ${avg(es.map(e=>e.dailyScore)).toFixed(1)}`}
function report(){return`ADHD HEALTH OS V4 REPORT\n\nEntries: ${db.entries.length}\nMedication adherence: ${adherence()}\nBest dose: ${bestDose()}\nAverage crash time: ${averageCrashTime()}\n\nInsights:\n${insights().map(x=>'- '+x).join('\n')}\n\n${weekly()}`}
function bar(label,vals,max=100){return`<div class="barWrap"><b>${label}</b>${vals.slice(-10).map(v=>`<div class="bar" style="width:${Math.max(3,Math.min(100,(v/max)*100))}%"></div>`).join('')||'<p class="muted">No data yet</p>'}</div>`}
function weightStats(){const es=db.entries.filter(e=>e.weight);if(es.length<2)return{trend:'--',rate:'--',eta:'--'};const ch=es.at(-1).weight-es[0].weight;return{trend:ch.toFixed(1)+'lb',rate:'tracking',eta:'--'}}
function render(){const e=current();set('dashAdhd',e.adhd.score+'/100');set('dashSleep',e.sleep.score+'/100');set('dashMed',e.med.score+'%');set('dashRisk',e.risk);set('dailyScore',e.dailyScore);set('systemSummary',`${e.risk} risk · daily ${e.dailyScore}/100`);set('recommendation',coach(e)[0]);if($('scoreCircle'))$('scoreCircle').className='scoreCircle '+(e.risk==='HIGH'?'high':e.risk==='MEDIUM'?'med':'low');set('qualityVal',str('quality')||8);set('medEffectiveness',e.med.score+'%');set('adherenceOut',adherence());set('medCrashRisk',e.med.risk);set('bestDoseOut',bestDose());set('durationOut',e.sleep.duration+'h');set('latencyOut',e.sleep.latency==null?'--':e.sleep.latency+'m');set('sleepScore',e.sleep.score+'/100');set('sleepDebtOut',e.sleep.debt+'h');set('healthScore',e.health.score+'/100');const ws=weightStats();set('weightTrend',ws.trend);set('weeklyLossOut',ws.rate);set('goalEtaOut',ws.eta);set('avgCrashTimeOut',averageCrashTime());set('avgCrashSeverityOut',avgCrashSeverity());set('productiveHyperfocusOut',db.entries.length?'tracking':'--');set('mostCommonHyperfocusOut',commonActivity());const fr=focusReadiness(e);set('focusReadiness',fr.score+'/100');set('focusReadinessPill',fr.label);set('focusRecommendation',coach(e).join(' '));html('workWindow',`<div class="insight"><b>Suggested window</b>${e.medTime?e.medTime+' onwards':'Morning'} until ${averageCrashTime()==='--'?'early afternoon':averageCrashTime()} for hardest tasks.</div>`);html('focusTimeline',`<div class="timelineItem"><div class="timelineTime">${e.medTime||'--'}</div><div class="timelineText">Medication window</div></div><div class="timelineItem"><div class="timelineTime">${averageCrashTime()}</div><div class="timelineText">Predicted crash window</div></div>`);html('actionPlan',coach(e).map(x=>`<div class="insight">${x}</div>`).join(''));html('tomorrowForecast',`<div class="insight"><b>Tomorrow forecast</b>Based on current data: focus ${fr.score}%, crash risk ${e.risk}, recommended caffeine under 150mg, protein breakfast recommended.</div>`);html('snapshot',bar('Daily',db.entries.map(x=>x.dailyScore))+bar('ADHD',db.entries.map(x=>x.adhd.score))+bar('Sleep',db.entries.map(x=>x.sleep.score)));html('insightList',insights().map(x=>`<div class="insight">${x}</div>`).join(''));set('weeklyReview',weekly());html('chartArea',bar('Medication',db.entries.map(x=>x.med.score))+bar('Mood',db.entries.map(x=>x.mood.score)));html('goalProgress',goals().map(g=>`<div class="barWrap"><b>${g.name}: ${g.val}/${g.target}</b><div class="progress"><div style="width:${clamp(g.val/g.target*100,0,100)}%"></div></div></div>`).join(''));renderJournal();renderRecent()}
function goals(){const e=current();return[{name:'ADHD',val:e.adhd.score,target:val('goalAdhd',75)},{name:'Sleep',val:e.sleep.duration,target:val('goalSleep',8)},{name:'Protein',val:val('proteinGrams'),target:val('goalProtein',180)},{name:'Steps',val:val('steps'),target:val('goalSteps',8000)}]}
function renderJournal(){html('journalResults',db.entries.filter(e=>e.journal&&(e.journal.win||e.journal.struggle||e.journal.observation)).slice(-5).reverse().map(e=>`<div class="entry"><b>${new Date(e.date).toLocaleDateString('en-GB')}</b>${e.journal.win||''} ${e.journal.struggle||''} ${e.journal.observation||''}</div>`).join('')||'<p class="muted">No journal entries yet.</p>')}
function renderRecent(){html('recentEntries',db.entries.slice(-5).reverse().map(e=>`<div class="entry"><b>${new Date(e.date).toLocaleString('en-GB')} · ${e.dailyScore}/100</b>ADHD ${e.adhd.score} · Sleep ${e.sleep.score} · Med ${e.med.score}%</div>`).join('')||'<p class="muted">No entries yet.</p>')}
function finishSetup(){db.profile={template:str('template'),med:str('setupMed'),goals:[...document.querySelectorAll('.goalSetup:checked')].map(x=>x.value)};if(db.profile.med) $('medName').value=db.profile.med;save();$('onboarding').classList.remove('show')}
function init(){set('todayTitle',new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'}));buildSliders(adhdMetrics,'adhdSliders');buildSliders(moodMetrics,'moodSliders');applySettings();if(!db.profile)$('onboarding').classList.add('show');document.querySelectorAll('input,select').forEach(el=>{el.addEventListener('input',render);el.addEventListener('change',render)});document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});$('finishSetupBtn').onclick=finishSetup;$('rerunSetupBtn').onclick=()=>$('onboarding').classList.add('show');$('saveFullEntryBtn').onclick=()=>{db.entries.push(current());save();alert('Entry saved')};$('resetFormBtn').onclick=()=>location.reload();$('generateReportBtn').onclick=()=>set('reportText',report());$('downloadReportBtn').onclick=()=>{const blob=new Blob([report()],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='adhd-health-report.txt';a.click()};$('exportBtn').onclick=$('exportJsonBtn').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='adhd-health-os-v4-backup.json';a.click()};$('importBtn').onclick=()=>{const f=$('importFile').files[0];if(!f)return alert('Choose backup first');const r=new FileReader();r.onload=e=>{db=JSON.parse(e.target.result);save();alert('Imported')};r.readAsText(f)};$('saveSettingsBtn').onclick=()=>{db.settings={theme:str('theme'),scheme:str('scheme')};applySettings();save()};$('clearBtn').onclick=()=>{if(confirm('Clear all data?')){db={entries:[],settings:db.settings,profile:null};save();location.reload()}};render()}
init();if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
