
(function(){
const $=id=>document.getElementById(id);
const storeKey='adhdHealthOSV41Fixed';
let db=JSON.parse(localStorage.getItem(storeKey)||'{"entries":[],"settings":{"theme":"light","scheme":"copper"},"profile":null}');
const adhdMetrics=[['focus','Focus',25,false],['initiation','Task initiation',20,false],['switching','Task switching',15,false],['emotional','Emotional regulation',15,false],['noise','Mental noise',15,true],['irritability','Irritability',10,true]];
const moodMetrics=[['mood','Mood'],['motivation','Motivation'],['anxiety','Anxiety'],['irritMood','Irritability']];
let vals={focus:5,initiation:5,switching:5,emotional:5,noise:5,irritability:5,mood:5,motivation:5,anxiety:5,irritMood:5};
function set(id,v){let e=$(id); if(e)e.textContent=v}
function html(id,v){let e=$(id); if(e)e.innerHTML=v}
function value(id,d=0){let e=$(id); let n=e?Number(e.value):d; return Number.isFinite(n)?n:d}
function text(id){let e=$(id); return e?e.value:''}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function mins(t){if(!t)return null;let p=t.split(':').map(Number);return p[0]*60+p[1]}
function fmt(m){if(m==null||Number.isNaN(m))return'--';m=Math.round(m)%1440;return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function diff(a,b){let x=mins(a),y=mins(b);if(x==null||y==null)return null;if(y<x)y+=1440;return y-x}
function save(){localStorage.setItem(storeKey,JSON.stringify(db));render()}
function buildSliders(list,wrapId){let wrap=$(wrapId); if(!wrap)return; wrap.innerHTML=''; list.forEach(m=>{let row=document.createElement('div'); row.className='row'; row.innerHTML='<div class="rowTop"><span>'+m[1]+'</span><span id="'+m[0]+'Val">'+vals[m[0]]+'</span></div><input id="'+m[0]+'" type="range" min="0" max="10" value="'+vals[m[0]]+'">'; wrap.appendChild(row); $(m[0]).addEventListener('input',e=>{vals[m[0]]=Number(e.target.value);set(m[0]+'Val',vals[m[0]]);render()})})}
function adhd(){let w=0; adhdMetrics.forEach(m=>w+=(m[3]?10-vals[m[0]]:vals[m[0]])*m[2]); let score=Math.round(w/10); let exec=Math.round((vals.focus+vals.initiation+vals.switching+vals.emotional)/40*100); return {score,exec}}
function sleep(){let start=text('sleepTime')||text('bedtime'); let dur=diff(start,text('wakeTime')); dur=dur==null?8:dur/60; let latency=text('sleepTime')&&text('bedtime')?diff(text('bedtime'),text('sleepTime')):null; let quality=value('quality',8), wakings=value('wakings',1); let ds=dur<=8?(dur/8)*50:50; let score=Math.round(clamp(ds+(quality/10)*40+Math.max(0,10-wakings*2),0,100)); return {score,duration:Number(dur.toFixed(1)),latency,debt:Number(Math.max(0,8-dur).toFixed(1))}}
function med(a,s){let crash=clamp(value('crashSeverity',5),0,10), caffeine=value('caffeine',100), protein=text('protein')==='yes', missed=text('missedDose')==='yes'; let score=Math.round(clamp(a.score*.7+(s.score-50)*.2-crash*3+(protein?5:-3)-(caffeine>300?10:caffeine>150?5:0)-(missed?25:0)+20,0,100)); let risk=score>=75&&crash<=3?'LOW':score>=60&&crash<=6?'MEDIUM':'HIGH'; return {score,risk,missed}}
function mood(){return {score:Math.round((vals.mood+vals.motivation+(10-vals.anxiety)+(10-vals.irritMood))/40*100)}}
function health(s){let score=50+(s.score>=75?20:s.score<60?-10:0)+(value('steps')>=value('goalSteps',8000)?10:0)+(text('gym')==='yes'?10:0)+(value('water')>=2?5:0); return {score:clamp(Math.round(score),0,100)}}
function current(){let a=adhd(),s=sleep(),m=med(a,s),mo=mood(),h=health(s); let daily=Math.round(a.score*.35+s.score*.2+m.score*.25+mo.score*.1+h.score*.1); let risk=s.score<60||m.risk==='HIGH'||value('crashSeverity',5)>=7?'HIGH':s.score<75||m.risk==='MEDIUM'?'MEDIUM':'LOW'; return {date:new Date().toISOString(),adhd:a,sleep:s,med:m,mood:mo,health:h,dailyScore:daily,risk,values:{...vals},medName:text('medName'),dose:text('dose'),medTime:text('medTime'),caffeine:value('caffeine',100),proteinBreakfast:text('protein')==='yes',crash:{time:text('crashTime'),severity:value('crashSeverity',5),duration:diff(text('crashTime'),text('recoveryTime'))||value('recoveryMinutes')},hyperfocus:{activity:text('hyperfocusActivity'),minutes:value('hyperfocusMinutes'),type:text('hyperfocusType')}}}
function adherence(){let es=db.entries.slice(-30); return es.length?Math.round(es.filter(e=>!e.med.missed).length/es.length*100)+'%':'--'}
function avgCrashTime(){let t=db.entries.filter(e=>e.crash&&e.crash.time).map(e=>mins(e.crash.time)); return t.length?fmt(avg(t)):'--'}
function avgCrashSeverity(){let v=db.entries.filter(e=>e.crash&&e.crash.severity).map(e=>e.crash.severity); return v.length?avg(v).toFixed(1)+'/10':'--'}
function bestDose(){let g={}; db.entries.forEach(e=>{if(e.dose){g[e.dose]=g[e.dose]||[];g[e.dose].push(e.med.score)}}); let s=Object.entries(g).map(x=>[x[0],avg(x[1])]).sort((a,b)=>b[1]-a[1]); return s.length?s[0][0]:'--'}
function commonActivity(){let c={}; db.entries.forEach(e=>{let a=e.hyperfocus&&e.hyperfocus.activity;if(a)c[a]=(c[a]||0)+1}); let s=Object.entries(c).sort((a,b)=>b[1]-a[1]); return s.length?s[0][0]:'--'}
function coach(e){let out=[]; if(e.sleep.score<60)out.push('Sleep is limiting focus. Keep important work early and light.'); if(e.med.risk==='HIGH')out.push('Crash risk is high. Prioritise food, hydration and avoid extra caffeine.'); if(e.adhd.exec<60)out.push('Executive function is low. Use 5-minute task starts.'); if(!out.length)out.push('Good readiness. Use the morning/early afternoon for high-value tasks.'); return out}
function insights(){let out=[]; if(db.entries.length<3)out.push('Need 3+ entries for stronger pattern insights.'); if(db.entries.some(e=>e.crash.time))out.push('Average crash time is '+avgCrashTime()+'.'); return out}
function weekly(){let es=db.entries.slice(-7); if(!es.length)return'No weekly data yet.'; return 'Entries: '+es.length+'\nADHD avg: '+avg(es.map(e=>e.adhd.score)).toFixed(1)+'\nSleep avg: '+avg(es.map(e=>e.sleep.score)).toFixed(1)+'\nMedication avg: '+avg(es.map(e=>e.med.score)).toFixed(1)+'%'}
function report(){return 'ADHD HEALTH OS V4.1 REPORT\n\nEntries: '+db.entries.length+'\nAdherence: '+adherence()+'\nBest dose: '+bestDose()+'\nAverage crash time: '+avgCrashTime()+'\n\n'+weekly()}
function bar(label,vals){return '<div class="barWrap"><b>'+label+'</b>'+(vals.length?vals.slice(-10).map(v=>'<div class="bar" style="width:'+Math.max(3,Math.min(100,v))+'%"></div>').join(''):'<p class="muted">No data yet</p>')+'</div>'}
function goals(){let e=current(); return [['ADHD',e.adhd.score,value('goalAdhd',75)],['Sleep',e.sleep.duration,value('goalSleep',8)],['Protein',value('proteinGrams'),value('goalProtein',180)],['Steps',value('steps'),value('goalSteps',8000)]]}
function render(){let e=current(); set('dashAdhd',e.adhd.score+'/100'); set('dashSleep',e.sleep.score+'/100'); set('dashMed',e.med.score+'%'); set('dashRisk',e.risk); set('dailyScore',e.dailyScore); set('systemSummary',e.risk+' risk · daily '+e.dailyScore+'/100'); set('recommendation',coach(e)[0]); $('scoreCircle').className='scoreCircle '+(e.risk==='HIGH'?'high':e.risk==='MEDIUM'?'med':'low'); set('qualityVal',text('quality')||8); set('medEffectiveness',e.med.score+'%'); set('adherenceOut',adherence()); set('medCrashRisk',e.med.risk); set('bestDoseOut',bestDose()); set('durationOut',e.sleep.duration+'h'); set('latencyOut',e.sleep.latency==null?'--':e.sleep.latency+'m'); set('sleepScore',e.sleep.score+'/100'); set('sleepDebtOut',e.sleep.debt+'h'); set('healthScore',e.health.score+'/100'); set('weightTrend','tracking'); set('weeklyLossOut','tracking'); set('goalEtaOut','--'); set('avgCrashTimeOut',avgCrashTime()); set('avgCrashSeverityOut',avgCrashSeverity()); set('productiveHyperfocusOut',db.entries.length?'tracking':'--'); set('mostCommonHyperfocusOut',commonActivity()); let fr=Math.round(e.adhd.exec*.4+e.sleep.score*.25+e.med.score*.25+e.mood.score*.1); set('focusReadiness',fr+'/100'); set('focusReadinessPill',fr>=80?'READY':fr>=60?'OK':fr>=40?'FRAGILE':'LOW'); set('focusRecommendation',coach(e).join(' ')); html('workWindow','<div class="insight"><b>Suggested window</b>Morning to '+(avgCrashTime()==='--'?'early afternoon':avgCrashTime())+' for hardest tasks.</div>'); html('focusTimeline','<div class="timelineItem"><div class="timelineTime">'+(e.medTime||'--')+'</div><div>Medication window</div></div><div class="timelineItem"><div class="timelineTime">'+avgCrashTime()+'</div><div>Predicted crash window</div></div>'); html('actionPlan',coach(e).map(x=>'<div class="insight">'+x+'</div>').join('')); html('tomorrowForecast','<div class="insight"><b>Tomorrow forecast</b>Focus '+fr+'%, crash risk '+e.risk+'. Protein breakfast recommended.</div>'); html('recentEntries',db.entries.slice(-5).reverse().map(x=>'<div class="entry"><b>'+new Date(x.date).toLocaleString('en-GB')+' · '+x.dailyScore+'/100</b>ADHD '+x.adhd.score+' · Sleep '+x.sleep.score+' · Med '+x.med.score+'%</div>').join('')||'<p class="muted">No entries yet.</p>'); html('insightList',insights().map(x=>'<div class="insight">'+x+'</div>').join('')); set('weeklyReview',weekly()); html('chartArea',bar('Daily',db.entries.map(x=>x.dailyScore))+bar('ADHD',db.entries.map(x=>x.adhd.score))); html('goalProgress',goals().map(g=>'<div class="barWrap"><b>'+g[0]+': '+g[1]+' / '+g[2]+'</b><div class="progress"><div style="width:'+clamp(g[1]/g[2]*100,0,100)+'%"></div></div></div>').join('')); html('journalResults','<p class="muted">Journal entries save with daily entry.</p>')}
function finishSetup(){db.profile={template:text('template'),med:text('setupMed')}; if(db.profile.med)$('medName').value=db.profile.med; save(); $('setupOverlay').classList.remove('show')}
function init(){set('todayTitle',new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})); buildSliders(adhdMetrics,'adhdSliders'); buildSliders(moodMetrics,'moodSliders'); if(!db.profile)$('setupOverlay').classList.add('show'); document.querySelectorAll('input,select').forEach(el=>{el.addEventListener('input',render);el.addEventListener('change',render)}); $('tabs').addEventListener('click',e=>{let b=e.target.closest('button[data-tab]'); if(!b)return; document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $(b.dataset.tab).classList.add('active')}); $('finishSetupBtn').onclick=finishSetup; $('rerunSetupBtn').onclick=()=>$('setupOverlay').classList.add('show'); $('saveEntryBtn').onclick=()=>{db.entries.push(current());save();alert('Entry saved')}; $('resetBtn').onclick=()=>location.reload(); $('generateReportBtn').onclick=()=>set('reportText',report()); $('downloadReportBtn').onclick=()=>{let blob=new Blob([report()],{type:'text/plain'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='adhd-health-report.txt';a.click()}; $('exportBtn').onclick=$('exportJsonBtn').onclick=()=>{let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='adhd-health-os-v4-backup.json';a.click()}; $('importBtn').onclick=()=>{let f=$('importFile').files[0]; if(!f)return alert('Choose backup first'); let r=new FileReader(); r.onload=e=>{db=JSON.parse(e.target.result);save();alert('Imported')}; r.readAsText(f)}; $('saveSettingsBtn').onclick=()=>{db.settings={theme:text('theme'),scheme:text('scheme')};save();alert('Settings saved')}; $('clearBtn').onclick=()=>{if(confirm('Clear all data?')){db={entries:[],settings:{theme:'light',scheme:'copper'},profile:null};save();location.reload()}}; render()}
init();
})();
